'use strict';
const TITLE_TYPES=[{id:'world',name:'World Championship (WWE / WHC)',base:20,month:3,def:3},{id:'mid',name:'Midcard Championship (IC / US / International)',base:10,month:1.5,def:1.5},{id:'tag',name:'Tag Team Championship',base:6,month:.75,def:1}];
const TROPHIES=[['wm','WrestleMania Main Event',25],['climax','PW Climax',23],['universe','Universe Tag Cup',20],['rumble','Royal Rumble',18],['kotr','King of the Ring',16],['mitb','Money in the Bank',14],['survivor','Survivor Series Sieg',10],['rawtag','RAW Tag Cup',8],['nomercy','No Mercy Koffer',6],['wmbr','WrestleMania Battle Royal Sieg',3]];
const RECORDS=[['longest','Neuer Rekord für längste Titelregentschaft',5],['double','Gleichzeitig zwei Titel gehalten',3],['grand','Grand Slam erreicht',4],['triple','Triple Crown erreicht',2],['undefeated','Ungeschlagene Turnierphase',2],['twoworld','Beide World Titles in einer Season gehalten',4],['record','Weiterer historischer Rekord',3]];
const TIERS=[['Jobber',0],['Undercarder',15],['Rising Star',30],['Mid Carder',45],['Top Guy',60],['SotS Kandidat',75],['Hall of Famer',90]];
const MAX={title:30,trophy:25,sport:20,work:10,history:10,impact:5};
const key='sots-calculator-candidates-v1';
const $=id=>document.getElementById(id);
const n=x=>Math.max(0,Number(x)||0);
const int=x=>Math.max(0,Math.floor(n(x)));
const fmt=x=>Number(x).toLocaleString('de-DE',{minimumFractionDigits:1,maximumFractionDigits:1});
const encode=x=>String(x).replace(/[&<>"']/g,chr=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[chr]));
const fresh=()=>({name:'',season:'',reigns:[],trophies:{},records:{},wins:0,draws:0,losses:0,workhorse:false,impact:0,wmWinner:false});
let state=fresh();let editingKey=null;let saved=loadSaved();
function loadSaved(){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x.filter(e=>e&&typeof e==='object'&&e.data&&typeof e.key==='string'):[]}catch{return []}}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved))}catch{alert('Die Rangliste konnte in diesem Browser nicht gespeichert werden. Bitte nutze Backup exportieren.')}}
function calculate(s){
 const titleRaw=(s.reigns||[]).reduce((sum,r)=>{const t=TITLE_TYPES.find(t=>t.id===r.type);return sum+(t?(int(r.wins)*t.base+n(r.months)*t.month+int(r.defenses)*t.def):0)},0);
 const trophyRaw=TROPHIES.reduce((sum,[id,,pts])=>sum+int(s.trophies?.[id])*pts,0)+(s.wmWinner&&int(s.trophies?.wm)>0?5:0);
 const historyRaw=RECORDS.reduce((sum,[id,,pts])=>sum+(s.records?.[id]?pts:0),0);
 const matches=int(s.wins)+int(s.draws)+int(s.losses);const rate=matches?int(s.wins)/matches:0;
 const parts={title:Math.min(30,titleRaw/2.5),trophy:Math.min(25,trophyRaw/2),sport:20*rate*Math.min(1,matches/20),work:Math.min(10,Math.min(10,matches/40*7)+(s.workhorse?3:0)),history:Math.min(10,historyRaw),impact:Math.min(5,n(s.impact)/10*5)};
 const score=Object.values(parts).reduce((a,b)=>a+b,0);const tier=TIERS.reduce((best,t)=>score>=t[1]?t[0]:best,TIERS[0][0]);return {parts,score,tier,matches,rate,titleRaw,trophyRaw,historyRaw}
}
function syncBasics(){['name','season','wins','draws','losses'].forEach(id=>{$(id).value=state[id]});$('impact').value=state.impact;$('workhorse').checked=state.workhorse;$('wmWinner').checked=state.wmWinner}
function renderReigns(){const parent=$('reigns');parent.replaceChildren();state.reigns.forEach((r,index)=>{
 const wrap=document.createElement('div');wrap.className='reign';
 wrap.innerHTML=`<div class="inline" style="margin-bottom:10px"><h3>Regentschaft ${index+1}</h3><button class="small ghost danger" type="button" data-remove>Entfernen ×</button></div><div class="field" style="margin-bottom:11px"><label>Titelkategorie</label><select data-field="type">${TITLE_TYPES.map(t=>`<option value="${t.id}">${encode(t.name)}</option>`).join('')}</select></div><div class="field" style="margin-bottom:11px"><label>Konkreter Titel (optional, z. B. IC Championship)</label><input type="text" data-field="titleName" placeholder="Titelbezeichnung"></div><div class="grid3"><div class="field"><label>Gewinne</label><input type="number" min="0" step="1" data-field="wins"></div><div class="field"><label>Monate</label><input type="number" min="0" step="0.1" data-field="months"></div><div class="field"><label>Verteidigungen</label><input type="number" min="0" step="1" data-field="defenses"></div></div>`;
 wrap.querySelector('[data-remove]').onclick=()=>{state.reigns.splice(index,1);renderReigns();update()};
 wrap.querySelectorAll('[data-field]').forEach(el=>{const field=el.dataset.field;el.value=r[field];el.addEventListener('input',()=>{r[field]=field==='type'||field==='titleName'?el.value:field==='months'?n(el.value):int(el.value);update()})});parent.append(wrap)
})}
function renderTrophies(){const parent=$('trophies');parent.replaceChildren();TROPHIES.forEach(([id,name,pts])=>{
 const row=document.createElement('div');row.className='trophy';const label=document.createElement('div');label.innerHTML=`<span class="subheading">${encode(name)}</span><div class="muted">${pts} Rohpunkte pro Erfolg</div>`;
 const group=document.createElement('div');group.className='counter';const minus=document.createElement('button');minus.className='small ghost';minus.textContent='−';minus.setAttribute('aria-label',`${name} reduzieren`);const number=document.createElement('span');number.className='count';number.textContent=int(state.trophies[id]);const plus=document.createElement('button');plus.className='small ghost';plus.textContent='+';plus.setAttribute('aria-label',`${name} hinzufügen`);
 minus.disabled=!int(state.trophies[id]);minus.onclick=()=>{state.trophies[id]=Math.max(0,int(state.trophies[id])-1);renderTrophies();update()};plus.onclick=()=>{state.trophies[id]=int(state.trophies[id])+1;renderTrophies();update()};group.append(minus,number,plus);row.append(label,group);parent.append(row)
});$('wmWinnerRow').classList.toggle('hidden',int(state.trophies.wm)===0);if(!int(state.trophies.wm))state.wmWinner=false;$('wmWinner').checked=state.wmWinner}
function renderRecords(){const parent=$('records');parent.replaceChildren();RECORDS.forEach(([id,name,pts])=>{
 const label=document.createElement('label');label.className='check';const box=document.createElement('input');box.type='checkbox';box.checked=!!state.records[id];box.onchange=()=>{state.records[id]=box.checked;update()};const text=document.createElement('span');text.textContent=name;const points=document.createElement('small');points.className='point';points.textContent=`+${pts}`;label.append(box,text,points);parent.append(label)
})}
function refreshInputs(){syncBasics();renderReigns();renderTrophies();renderRecords();update()}
function update(){const c=calculate(state);$('matches').textContent=c.matches;$('winrate').textContent=`${fmt(c.rate*100)} %`;$('sportPoints').textContent=fmt(c.parts.sport);$('titlePoints').textContent=`${fmt(c.parts.title)} / 30`;$('trophyPoints').textContent=`${fmt(c.parts.trophy)} / 25`;$('workPoints').textContent=`${fmt(c.parts.work)} / 10`;$('recordPoints').textContent=`${fmt(c.parts.history)} / 10`;$('impactValue').textContent=`${n(state.impact)} / 10`;
 const name=state.name.trim()||'Unbenannter Superstar';$('scoreIdentity').textContent=`${name}${state.season?' · '+state.season:''}`;$('totalTop').innerHTML=`${fmt(c.score)} <span style="font-size:16px;letter-spacing:0;font-weight:500">/ 100</span>`;$('totalBottom').innerHTML=$('totalTop').innerHTML;$('finalName').textContent=$('scoreIdentity').textContent;$('tierLabel').textContent=c.tier;$('finalBar').style.width=Math.min(100,c.score)+'%';$('tierText').textContent=TIERS.map(t=>t[0]).join(' · ');$('tierSegments').innerHTML=TIERS.map(t=>`<div class="${t[0]===c.tier?'active':''}" title="${t[0]} (ab ${t[1]} Punkten)"></div>`).join('');
 const labels=[['title','Championships'],['trophy','Trophäen'],['sport','Siegquote'],['work','Workrate'],['history','Rekorde'],['impact','Season-Einfluss']];$('breakdown').innerHTML=labels.map(([id,label])=>`<div><div class="inline"><span>${label}</span><b>${fmt(c.parts[id])} / ${MAX[id]}</b></div><div class="bar"><div style="width:${Math.min(100,c.parts[id]/MAX[id]*100)}%"></div></div></div>`).join('');$('saveCandidate').textContent=editingKey?'✓ Änderungen speichern':'＋ Zur Rangliste hinzufügen';return c
}
function makeKey(){return 'candidate-'+Date.now()+'-'+Math.floor(Math.random()*1e8)}
function resetForm(){state=fresh();editingKey=null;refreshInputs();$('name').focus()}
function saveCandidate(){const name=state.name.trim();if(!name){alert('Bitte zuerst einen Wrestlernamen eingeben.');$('name').focus();return}let keyEntry=editingKey;if(!keyEntry){const duplicate=saved.find(e=>e.data.name.trim().toLowerCase()===name.toLowerCase()&&e.data.season.trim().toLowerCase()===state.season.trim().toLowerCase());if(duplicate&&!confirm('Dieser Wrestler ist für die Season bereits gespeichert. Vorhandenen Eintrag ersetzen?'))return;keyEntry=duplicate?.key||makeKey()}saved=saved.filter(e=>e.key!==keyEntry);saved.push({key:keyEntry,data:JSON.parse(JSON.stringify(state))});editingKey=keyEntry;persist();renderRanking();update()}
function renderRanking(){const ordered=[...saved].sort((a,b)=>calculate(b.data).score-calculate(a.data).score);$('savedCount').textContent=`${ordered.length} Wrestler`;$('ranking').replaceChildren();if(!ordered.length){$('ranking').innerHTML='<div class="empty">Noch keine Kandidaten gespeichert.</div>';return}ordered.forEach((entry,i)=>{
 const score=calculate(entry.data);const row=document.createElement('div');row.className='rank-row';const rank=document.createElement('strong');rank.textContent=i+1;const name=document.createElement('b');name.textContent=entry.data.name||'Unbekannt';const meta=document.createElement('small');meta.textContent=`${entry.data.season||'Ohne Season'} · ${score.tier} · ${score.matches} Matches · ${fmt(score.rate*100)} %`;name.append(meta);const pts=document.createElement('div');pts.className='points';pts.textContent=fmt(score.score);const actions=document.createElement('div');actions.className='rank-actions';const edit=document.createElement('button');edit.className='ghost';edit.textContent='✎';edit.title='Bearbeiten';edit.setAttribute('aria-label',`${entry.data.name} bearbeiten`);edit.onclick=()=>{state=JSON.parse(JSON.stringify(entry.data));editingKey=entry.key;refreshInputs();scrollTo({top:0,behavior:'smooth'})};const del=document.createElement('button');del.className='ghost danger';del.textContent='×';del.title='Entfernen';del.setAttribute('aria-label',`${entry.data.name} entfernen`);del.onclick=()=>{if(confirm(`${entry.data.name} aus der Rangliste entfernen?`)){saved=saved.filter(e=>e.key!==entry.key);if(editingKey===entry.key)editingKey=null;persist();renderRanking();update()}};actions.append(edit,del);row.append(rank,name,pts,actions);$('ranking').append(row)
})}
function analysis(){const c=calculate(state);return `${state.name||'Unbenannter Superstar'} | ${state.season||'Season unbekannt'}\nSingles: ${int(state.wins)}–${int(state.draws)}–${int(state.losses)} (${c.matches} Matches; ${fmt(c.rate*100)} % Siege)\n\nTITEL\n${state.reigns.map(r=>{const t=TITLE_TYPES.find(t=>t.id===r.type);return `• ${r.titleName||t?.name||r.type}: ${int(r.wins)} Titelgewinn(e), ${n(r.months)} Monate, ${int(r.defenses)} Verteidigungen`}).join('\n')||'Keine'}\n\nTROPHÄEN\n${TROPHIES.filter(([id])=>int(state.trophies[id])>0).map(([id,name])=>`• ${name} × ${int(state.trophies[id])}`).join('\n')||'Keine'}${state.wmWinner&&int(state.trophies.wm)>0?'\n• WrestleMania-Main-Event gewonnen':''}\n\nREKORDE\n${RECORDS.filter(([id])=>state.records[id]).map(([,name])=>'• '+name).join('\n')||'Keine'}\n\nWorkhorse: ${state.workhorse?'Ja':'Nein'} | Season-Einfluss: ${state.impact}/10\n\nPUNKTE\nChampionships: ${fmt(c.parts.title)}/30\nTrophäen: ${fmt(c.parts.trophy)}/25\nSiegquote: ${fmt(c.parts.sport)}/20\nWorkrate: ${fmt(c.parts.work)}/10\nRekorde: ${fmt(c.parts.history)}/10\nSeason-Einfluss: ${fmt(c.parts.impact)}/5\nGESAMT: ${fmt(c.score)}/100 (${c.tier})`}
async function copyAnalysis(){const txt=analysis();try{await navigator.clipboard.writeText(txt);alert('Auswertung wurde kopiert.')}catch{const area=document.createElement('textarea');area.value=txt;document.body.append(area);area.select();try{document.execCommand('copy');alert('Auswertung kopiert.')}catch{prompt('Bitte Text kopieren:',txt)}area.remove()}}
function download(name,text,type){const blob=new Blob(['\ufeff',text],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function exportCSV(){const cols=['Rang','Superstar','Season','Score','Einstufung','Siege','Draws','Niederlagen','Matches','Siegquote (%)','Titelpunkte','Trophäenpunkte','Sportpunkte','Workratepunkte','Rekordpunkte','Season-Einfluss'];const items=[...saved].sort((a,b)=>calculate(b.data).score-calculate(a.data).score);const rows=items.map((e,i)=>{const s=e.data,c=calculate(s),p=c.parts;return [i+1,s.name,s.season,c.score.toFixed(2),c.tier,int(s.wins),int(s.draws),int(s.losses),c.matches,(c.rate*100).toFixed(2),p.title.toFixed(2),p.trophy.toFixed(2),p.sport.toFixed(2),p.work.toFixed(2),p.history.toFixed(2),p.impact.toFixed(2)]});const quote=x=>'"'+String(x).replace(/"/g,'""')+'"';download('SotS_Rangliste.csv',[cols,...rows].map(row=>row.map(quote).join(';')).join('\r\n'),'text/csv;charset=utf-8')}
function exportJSON(){download('SotS_Backup.json',JSON.stringify({app:'sots-calculator',version:1,created:new Date().toISOString(),candidates:saved},null,2),'application/json')}
function importJSON(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result);if(parsed.app!=='sots-calculator'||!Array.isArray(parsed.candidates))throw Error('Ungültiges SotS-Backup');if(!confirm(`Backup mit ${parsed.candidates.length} Kandidaten importieren? Die aktuelle Rangliste wird ersetzt.`))return;saved=parsed.candidates.filter(e=>e&&typeof e.key==='string'&&e.data&&typeof e.data==='object'&&Array.isArray(e.data.reigns));persist();renderRanking();alert(`${saved.length} Kandidaten importiert.`)}catch(e){alert('Import fehlgeschlagen: '+e.message)}finally{$('jsonImport').value=''}};reader.readAsText(file)}
['name','season'].forEach(id=>$(id).addEventListener('input',e=>{state[id]=e.target.value;update()}));
['wins','draws','losses'].forEach(id=>$(id).addEventListener('input',e=>{state[id]=int(e.target.value);update()}));
$('impact').addEventListener('input',e=>{state.impact=int(e.target.value);update()});
$('workhorse').addEventListener('change',e=>{state.workhorse=e.target.checked;update()});
$('wmWinner').addEventListener('change',e=>{state.wmWinner=e.target.checked;update()});
$('addReign').onclick=()=>{state.reigns.push({type:'mid',titleName:'',wins:1,months:0,defenses:0});renderReigns();update()};
$('resetTop').onclick=resetForm;$('resetSide').onclick=resetForm;
$('saveCandidate').onclick=saveCandidate;$('copyAnalysis').onclick=copyAnalysis;
$('csvExport').onclick=exportCSV;$('jsonExport').onclick=exportJSON;
$('jsonImportButton').onclick=()=>$('jsonImport').click();$('jsonImport').onchange=e=>importJSON(e.target.files[0]);
$('clearRanking').onclick=()=>{if(saved.length&&confirm('Wirklich die gesamte gespeicherte Rangliste löschen?')){saved=[];editingKey=null;persist();renderRanking();update()}};
refreshInputs();renderRanking();
